#!/bin/bash

# JazzyPop Pre-Economy Remodel Backup Script
# This script creates a backup of the current state before implementing the economy design changes

echo "🎮 JazzyPop Pre-Economy Backup Script"
echo "===================================="
echo ""

# Set date for backup naming
BACKUP_DATE=$(date +"%Y%m%d_%H%M%S")
BACKUP_DIR="jazzypop-backup-pre-economy-${BACKUP_DATE}"

# Create backup directory
echo "📁 Creating backup directory: ${BACKUP_DIR}"
mkdir -p "${BACKUP_DIR}"

# Define directories to backup
echo "📦 Backing up application files..."

# Backup frontend directory
cp -r frontend "${BACKUP_DIR}/"
echo "  ✓ Backed up frontend"

# Backup backend directory
cp -r backend "${BACKUP_DIR}/"
echo "  ✓ Backed up backend"

# Backup documentation
echo ""
echo "📄 Backing up documentation..."
cp *.md "${BACKUP_DIR}/" 2>/dev/null || echo "  ℹ️  No markdown files in root"

# Create a backup manifest
echo ""
echo "📝 Creating backup manifest..."
cat > "${BACKUP_DIR}/BACKUP_MANIFEST.md" << EOF
# JazzyPop Pre-Economy Backup Manifest

**Backup Date**: ${BACKUP_DATE}
**Backup Purpose**: Preserve state before economy design system implementation

## Backed Up Components

### Frontend (frontend)
- All components (CardManager, GenericCard, EconomyManager, etc.)
- All styles (card.css, dashboard.css, etc.)
- All scripts (dashboard.js, etc.)
- All images and assets

### Backend
- API endpoints
- Database schemas
- All Python services

### Key Files to Note
- \`frontend/src/components/GenericCard.js\` - Current card structure
- \`frontend/src/styles/components/card.css\` - Current card styles
- \`frontend/src/components/CardManager.js\` - Card management logic
- \`backend/main.py\` - API endpoints

## Pre-Economy State

### Current Features
- Four quiz modes with unique visual styles (PoqPoq, Chaos, Zen, Speed)
- Category-based card icons
- Basic cost display in cards
- Play button with mode-specific styling

### What Will Change
- Border colors (from decorative to functional)
- Cost display location and detail
- Event badge system
- Rewards display location
- Button states for events

## Restoration Instructions

To restore this backup:
\`\`\`bash
# Remove current directories
rm -rf frontend backend

# Copy backup directories back
cp -r ${BACKUP_DIR}/frontend ./
cp -r ${BACKUP_DIR}/backend ./
\`\`\`

---
Generated by backup-pre-economy.sh
EOF

# Create a git tag if in a git repository
if [ -d .git ]; then
    echo ""
    echo "🏷️  Creating git tag..."
    git tag -a "pre-economy-${BACKUP_DATE}" -m "Pre-economy design implementation backup"
    echo "  ✓ Created git tag: pre-economy-${BACKUP_DATE}"
fi

# Compress the backup
echo ""
echo "🗜️  Compressing backup..."
tar -czf "${BACKUP_DIR}.tar.gz" "${BACKUP_DIR}"
echo "  ✓ Created compressed backup: ${BACKUP_DIR}.tar.gz"

# Final summary
echo ""
echo "✅ Backup Complete!"
echo ""
echo "📊 Backup Summary:"
echo "  - Backup directory: ${BACKUP_DIR}"
echo "  - Compressed file: ${BACKUP_DIR}.tar.gz"
if [ -d .git ]; then
    echo "  - Git tag: pre-economy-${BACKUP_DATE}"
fi
echo ""
echo "💡 Next steps:"
echo "  1. Verify backup contents"
echo "  2. Begin economy design implementation"
echo "  3. Use UNIFIED_ECONOMY_DESIGN.md as reference"
echo ""
echo "Good luck with the economy remodel! 🚀"